name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cbeloni
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: danielr1996/envsubst-action@1.0.0
        env:
            MYSQL_HOST: '${{ secrets.MYSQL_HOST_MGC }}'
            MYSQL_DATABASE: '${{ secrets.MYSQL_DATABASE }}'
            MYSQL_USER: '${{ secrets.MYSQL_USER }}'
            MYSQL_PASSWORD: '${{ secrets.MYSQL_PASSWORD }}'
        with:
          input: .env.template
          output: .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cbeloni/datasaude-api-ml-amd64:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_MGC }}" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_MGC }}      

      - name: Apply Kubernetes manifests
        run: |          
          kubectl apply -f datasaude-api-ml-mgc.yaml --insecure-skip-tls-verify
          kubectl rollout restart deployment/datasaude-api-ml --insecure-skip-tls-verify